package com.example.kotldemo

import com.amazonaws.services.dynamodbv2.datamodeling.*
import org.springframework.data.annotation.Id

@DynamoDBTable(tableName = "Customers")
data class CustomerEntry(
        @field:Id
        @DynamoDBIgnore
        val id: CustomerEntryId = CustomerEntryId()
) {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "customerId")
    fun getCustomerId() = id.customerId

    fun setCustomerId(customerId: String) {
        id.customerId = customerId
    }

    @DynamoDBRangeKey(attributeName = "customerKey")
    fun getCustomerKey() = id.customerKey

    fun setCustomerKey(customerKey: String) {
        id.customerKey = customerKey
    }

    @get:DynamoDBAttribute
    var customerValue: String? = null
}